name: Cursed Metrics

on:
  schedule:
    - cron: '0 5 * * *'  # runs daily at 5:00 UTC
  workflow_dispatch:

jobs:
  cursed-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Generate Cursed Metrics
        run: |
          echo "Generating cursed logs..."
          python3 generate_cursed_metrics.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name "Cursed Metrics Bot"
          git config --global user.email "bot@metrics.void"
          git add README.md
          git commit -m "🩻 updated cursed metrics"
          git push
